# Generated by Django 3.0.6 on 2020-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_types',
            name='body_name',
            field=models.CharField(choices=[('sport', 'Sport'), ('touring', 'Touring'), ('standard', 'Standard'), ('cruiser', 'Cruiser'), ('dual-purpose', 'Dual-Purpose'), ('dirt_bike', 'Dirt Bike'), ('others', 'Others')], default='others', max_length=30),
        ),
    ]
