# Generated by Django 3.0.6 on 2020-07-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.Supplies'),
            preserve_default=False,
        ),
    ]
