# Generated by Django 3.0.6 on 2020-08-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20200731_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
