# Generated by Django 3.1 on 2020-09-23 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_auto_20200801_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
