# Generated by Django 3.1 on 2020-09-23 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20200923_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
