# Generated by Django 3.1 on 2020-10-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_supplies_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='profit',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
