# Generated by Django 3.1 on 2020-10-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.subcategories'),
            preserve_default=False,
        ),
    ]
